FROM maven:3-eclipse-temurin-17

WORKDIR /app

# Copia il repository Maven locale (dipendenze offline)
COPY .m2 .m2

# Copia il codice sorgente
COPY pom.xml ./
COPY src ./src
COPY frontend ./frontend

EXPOSE 8080

CMD ["mvn", "spring-boot:run", "-Dmaven.repo.local=.m2"]
